### ISSUE TITLE
Karank when running through docker doesn't send dicom images to kheops

### ISSUE THREAD

**Issue by RajaMuneerBaigal** [OsiriX-Foundation/karnak-docker#2]
Hi, 
I hope you are doing great. I am trying to set up Karnak and Kheops altogether. I have set up Karnak on IP:8081 and my Kheops is running on my IP:80/IP. I am trying to send dicom images using my local installed Weasis to Karnak and then from Karnak to Kheops albums but I see that the images are sent to Karnak but I don't see them in Kheops albums not sure what am I doing wrong. I followed the following instructions to set up Kheops and Karnak. Please note I have setup source as KARNAK-GATEWAY and destination as kheops as stow as shown in the screenshots attached below. Let me know what I am doing wrong or is it possible or not to send dicom images using local installed weasis to karnak and then to kheops.Any help would be much appreciated. Thanks

https://docs.kheops.online/docs/installation
https://osirix-foundation.github.io/karnak-documentation/docs/installation

Here are the screenshots attached:
![image](https://github.com/OsiriX-Foundation/karnak-docker/assets/105891199/35dca9f2-162d-49db-9878-b18a18fc811c)
![image](https://github.com/OsiriX-Foundation/karnak-docker/assets/105891199/fe9480f0-53a2-4ac2-ae83-014421c4d493)
![image](https://github.com/OsiriX-Foundation/karnak-docker/assets/105891199/340e0a1c-88dc-45f2-8e89-5e65dd18d7b6)
![image](https://github.com/OsiriX-Foundation/karnak-docker/assets/105891199/986355ed-52ac-4c84-9c53-6ab8bb62363d)
![image](https://github.com/OsiriX-Foundation/karnak-docker/assets/105891199/aca8f77b-8c05-4df7-aa46-588252f73579)

**Comment by nroduit** [comment]
You must add a [STOW destination](https://osirix-foundation.github.io/karnak-documentation/docs/userguide/gateway#stow-destination) where the token must be created in Kheops dicom albums.

You should look in the [logs files](https://weasis.org/en/tutorials/logging/).

**Comment by RajaMuneerBaigal** [comment]
> You must add a [STOW destination](https://osirix-foundation.github.io/karnak-documentation/docs/userguide/gateway#stow-destination) where the token must be created in Kheops dicom albums.
> 
> You should look in the [logs files](https://weasis.org/en/tutorials/logging/).

I created the token and added it as per the docs shown in the attached screenshot above after the bearer I pasted the token but still did not get any images in the albums in Kheops. I checked the logs as well can't see any errors in the docker logs but here are the logs from weasis after I configured it to write error logs to file.
```
cat default.log 
14.05.2024 14:13:27.517 *ERROR* [Dicom Send task-pool-5-thread-1] org.dcm4che3.tool.storescu.StoreSCU: Cannot send filejava.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)

14.05.2024 14:13:27.522 *ERROR* [Dicom Send task-pool-5-thread-1] org.weasis.core.util.FileUtil: Cannot close AutoCloseablejava.io.EOFException: null
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:69)
	at org.dcm4che3.net.PDUDecoder.readFully(PDUDecoder.java:225)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:159)
	at org.dcm4che3.net.Association$2.run(Association.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

14.05.2024 14:13:27.524 *ERROR* [Dicom Send task-pool-5-thread-1] org.weasis.core.util.FileUtil: Cannot close AutoCloseablejava.io.EOFException: null
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:69)
	at org.dcm4che3.net.PDUDecoder.readFully(PDUDecoder.java:225)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:159)
	at org.dcm4che3.net.Association$2.run(Association.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

14.05.2024 14:13:27.525 *ERROR* [Dicom Send task-pool-5-thread-1] org.weasis.core.util.FileUtil: Cannot close AutoCloseablejava.io.EOFException: null
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:69)
	at org.dcm4che3.net.PDUDecoder.readFully(PDUDecoder.java:225)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:159)
	at org.dcm4che3.net.Association$2.run(Association.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

```

**Comment by nroduit** [comment]
According to the logs, the connection is closed during transfer at network level. This may be due to a firewall.

On Kheops, sending to DICOM C-Store is not authorized (visible in your logs).

The screenshots above show a configuration in both URL Credentials and headers. With Kheops, only the Barer Token is accepted.

**Comment by RajaMuneerBaigal** [comment]
> According to the logs, the connection is closed during transfer at network level. This may be due to a firewall.
> 
> On Kheops, sending to DICOM C-Store is not authorized (visible in your logs).
> 
> The screenshots above show a configuration in both URL Credentials and headers. With Kheops, only the Barer Token is accepted.

Thank you the issue has been resolved now. Seemed like it had to do something with the transfer syntax type for some images it was transferring with the original syntax but for some I had to changed it to other option. Thanks for your time
